---
# tasks file for ansible-role-contrast/

#- include_vars: "secrets/jenkins_access_secrets.yml"

#- set_fact: prod_url="https://app.contrastsecurity.com/Contrast/api/engine/default/java"

- name: Create directory for contrast agent
  file: path={{ contrast_agent_path }}/contrast state=directory
  sudo: True

- name: Download java agent from production
  action: shell curl -v -HAccept:application/json -HAPI-Key:{{ contrast_api_key }} -HAuthorization:{{ contrast_authorization_key }} {{ contrast_prod_url }} > {{ contrast_agent_path }}/contrast/contrast.jar
  sudo: True

- name: Add to JAVA_OPTS
  shell: export JAVA_OPTS="$JAVA_OPTS -javaagent:{{ contrast_agent_path }}/contrast/contrast.jar"
